- backend/src/models/department.entity.ts
- backend/src/models/form.entity.ts
- backend/src/models/formInstance.entity.ts
- backend/src/models/position.entity.ts
- backend/src/models/signatureChainLink.entity.ts
- backend/src/models/signatureRequestLink.entity.ts
This PR adds explicit foreign key columns in order to allow services to save new entities with foreign key references by using the foreign key id values instead of the full referenced foreign entity. This issue arose when we were creating services/entity repositories - this solution means we won't have to query for the foreign entity separately just to save another entity to a table.
Closes [Create database schema for backend](https://trello.com/c/ynAzefkR/6-create-database-schema-for-backend)
Please delete options that are not relevant.
Verify all tables and their schemas by manually checking each table's schema after setting up the DB by running `yarn start:dev`
> Add explicit foreign key columns to use when saving new entities to tables

- apps/server/prisma/seed.ts
- apps/server/src/app.controller.ts
- apps/server/src/auth/auth.decorators.ts
- apps/server/src/auth/entities/user.entity.ts
- apps/server/src/auth/public.decorator.ts
- apps/server/src/employees/entities/employee.entity.ts
- apps/server/src/form-instances/entities/form-instance.entity.ts
- apps/server/src/form-instances/form-instances.controller.ts
- apps/server/src/form-instances/form-instances.service.spec.ts
- apps/server/src/form-instances/form-instances.service.ts
- apps/server/src/form-templates/dto/create-form-template.dto.ts
- apps/server/src/form-templates/dto/update-form-template.dto.ts
- apps/server/src/form-templates/form-templates.service.ts
- apps/server/src/signatures/entities/signature.entity.ts
- apps/web/src/client/models/CreateFormTemplateDto.ts
- apps/web/src/client/models/EmployeeEntity.ts
- apps/web/src/client/services/FormInstancesService.ts
Closes [Add authentication/create routes to fetch form instances for a specific employee](https://trello.com/c/xu9kRUKm/58-add-authentication-create-routes-to-fetch-form-instances-for-a-specific-employee)
Added /me routes for form instances to get instances for currently authenticated user.
Added seeding for form instances
Partial unit test coverage.
^
- Try authenticating and testing out the `/form-instance/me` and `/form-instance/created/me` routes using the accounts `email1@gmail.com` and `email2@gmail.com` in the Swagger API.
- CI passing
> Add routes to get form instances for current user

- apps/web/src/components/AvatarMap.tsx
Pending text should appear if there is not a signature.
added pending text
> pending stuff

- apps/web/src/hooks/useForm.ts
Closes [story](https://trello.com/c/qTAHzBFB/124-fix-todo-to-reflect-forms-that-are-ready-to-be-signed)
Previously, the todo section on the dashboard displayed the form as ready to sign for every user in the signature list. Users should only see forms they are ready to sign (they are first user in the signature list who has not signed the form yet).
Changed the useForm hook to filter and sort forms to only return todo forms such that the user is first in the signature list.
Created a form and tested with users who are first and not first.
> Fix todo to reflect forms that are ready to be signed

- .vscode/settings.json
- apps/web/src/components/FormCard.tsx
- apps/web/src/components/OverviewRow.tsx
- apps/web/src/pages/index.tsx
Closes [story](https://trello.com/c/FwYiPTGw/118-fix-form-instance-cards-truncate-title-card-sizing)
Form cards text is lopsided when too long.
Truncate form cards text when too long.
Made some really long form texts and they were truncated.
> Fix form cards text

- apps/web/src/components/FormInstance.tsx
Closes [story](https://www.notion.so/sandboxnu/0ff8d90722bf435db9475c07e2311a2b?v=f7473b246d1742e395395cf955037121&p=422efc613ab74950814fabaa68f03808&pm=s)
The approval button on pages where the form instance was not originated allowing people to submit false completions
Adding an additional conditional check lol
Also prettier formatting caused this PR to be a bit bloated
[ ❌ ] This PR adds new dependencies
Manual Testing,
Create a new form, and on the last person to submit approval, see …
> adding extra check in the form instance approval button

- apps/web/src/components/createFormInstance/SignatureDropdown.tsx
Closes [Fix Directory Search](https://www.notion.so/sandboxnu/0ff8d90722bf435db9475c07e2311a2b?v=f7473b246d1742e395395cf955037121&p=0d1a04364054475095b9b79829b92f0e&pm=s)
Previously for the drop downs on the create Form instance components, the search for the drop down only searched on the positions of all the potential assignees. This needed to be changed to include the employee name as well so you could search for both their name and position. 
Updated the SignatureDropDown component to include the employeeName and position for the label to be searched upon
Manual testing: try the search now in the …
> Fix Directory Search

- apps/web/src/components/FormCard.tsx
- apps/web/src/components/createFormTemplate/CreateFormTemplateModal.tsx
- apps/web/src/hooks/useForm.ts
Closes [story](https://www.notion.so/sandboxnu/Form-Template-Modal-Styling-Fixes-1d19a3a3f2084ba8b049c8527a45e675?pvs=4)
Previously, the create form template modal layout was unreliable at different screen heights and widths.
The layout is standardized with flex and follows figma design more closely.
Different screen sizes, creating form template still works.
> Fix create form template modal styling and reset on modal close

- .github/workflows/main.yml
- apps/server/package.json
- apps/server/prisma/seed.ts
- apps/server/src/form-instances/form-instances.controller.spec.ts
- apps/server/src/form-instances/form-instances.module.ts
- apps/server/src/form-instances/form-instances.service.spec.ts
- apps/server/src/form-instances/form-instances.service.ts
- apps/server/src/postmark/postmark.service.ts
- yarn.lock
> retry postmark

- apps/server/prisma/seed.ts
- apps/web/src/components/FormInstance.tsx
- apps/web/src/components/createFormInstance/CreateFormInstanceModal.tsx
- apps/web/src/components/createFormTemplate/CreateFormTemplateModal.tsx
- apps/web/src/hooks/useStorage.ts
- apps/web/src/services/storage.service.ts
Remove mock storage implementation
Changed storage to real MFA storage now that the keys work
> storage works

- apps/web/src/pages/api/auth/[...nextauth].ts
No NextAuth secret, which may be causing deployment to not be able to signin. 
Add Nextauth secret.
Manual tests.
> Add Nextauth Secret

- apps/web/src/components/FormImageCard.tsx
- apps/web/src/components/FormList.tsx
- apps/web/src/components/OverviewRow.tsx
- apps/web/src/pages/index.tsx
I got rid of the row width calculation, so instead the See All button and cards can go all the way to the end, with 30px of padding on the right.  The cards also wrap now as the window is resized.  I also changed the title for the card section to say "form" instead of "forms" if there's only one.
The spacing of the cards and the See All button were not up to date with the Figma files.
Closes [#167]
I looked at the spacing of the elements and tried resizing the window to make sure they move between rows.
> 167 bug adjust form image card and see all button width

- apps/server/src/form-instances/form-instances.service.ts
- apps/web/src/components/FormImageCard.tsx
- apps/web/src/context/AuthContext.tsx
- apps/web/src/hooks/useForm.ts
- apps/web/src/utils/formInstanceUtils.ts
Update useForm hook to set todo, pending, and completed forms correctly: 
Todo
- Your turn to sign the form
- You are the originator and the form is ready to be approved
Pending
- Originator: forms that are still in progress of being signed
- Member of chain: form that are still in the progress of being signed or awaiting approval
Completed
- Approved forms that everyone can see in the chain
Update frontend to reflect needs approval status.
Reduce confusion of those categories and make it consistent with what client wants.
Closes [#172]
Created, signed, and approved forms with various edge cases.
This change assumes that we can only assign a user to sign a form once.
> 172 feature reconfigure form signing approving and category logic

- apps/web/src/components/AzureSignin.tsx
- apps/web/src/context/AuthContext.tsx
- apps/web/src/context/types.ts
Fixes crash when registering with an account that doesn't exist.
Register caused a crash due to accounts not being set within msal instance.
Closes [#Did not create a ticket for this oops]
I reset the database 5 times and logged in with azure, no crashes observed.
Before, we would crash when trying to register the first time with a new account.
> [BUG] Move all login logic into authcontext so msal instance is declared once

- apps/server/src/signature-fields/signature-fields.controller.spec.ts
- apps/server/src/signature-fields/signature-fields.service.spec.ts
Part 1/? of test rewrites-- this PR includes new tests for `signature-fields.service` and `signature-fields.controller` -- these ones are unaffected by recent merges to main so pushing these first, not sure if the coverage on these is spotless but eh. 
Closes [#137]
run `yarn test`
- [X ] Bug fix (non-breaking change which fixes an issue)
- [X ] My code follows the code style of this project.
- [X ] I have added tests to cover my changes.
- [X ] All new and existing tests passed.
> #137 write and fix tests part 1/? - signature-fields

- apps/server/src/form-instances/form-instances.service.ts
- apps/web/src/components/FormImageCard.tsx
- apps/web/src/components/FormInstance.tsx
- apps/web/src/components/NavBar.tsx
- apps/web/src/context/AuthContext.tsx
- apps/web/src/context/types.ts
- apps/web/src/hooks/useForm.ts
- apps/web/src/utils/formInstanceUtils.ts
- Fix form hover blur
- Users can see forms assigned to their departments and positions, and can sign those forms
- The email notification system is broken so temp fix to not send emails to non users
- Also temporarily added dept id to user type in AuthContext, we can probably do this in the backend later
- This was broken, so users who were assigned forms couldn't see it
Closes [#didnt make one rip]
SIgning forms
> Fix form blur, allow users who are in a position or department to see forms they are assigned

- apps/server/prisma/seed.ts
- apps/server/src/form-instances/form-instances.service.ts
- apps/server/src/postmark/postmark.service.ts
- apps/web/src/components/AvatarMap.tsx
- apps/web/src/components/FormInstance.tsx
- apps/web/src/utils/formInstanceUtils.ts
- Send email to all emails in user list when `USER_LIST` signer type is next.
- When a signature is signed, the avatar now shows the initials of the signer
- Email notifications for `USER_LIST`
- Avatar for signed signatures
Closes [#196 ]
- New seed file form instance `Staffing Requisition Form Instance` with `USER_LIST` as second signature, signing as the first user results in email to all users in the list
- Signing as a position, department, or list changes the avatar to initials
Before signing:
After signing:
- [] Bug fix (non-breaking change which fixes an issue)
> 196 handle email notifications for user list, fix some avatars when a user signs

- apps/server/prisma/seed.ts
- apps/server/src/positions/positions.controller.ts
- apps/server/src/positions/positions.service.ts
- apps/web/src/client/models/FormInstanceEntity.ts
- apps/web/src/client/services/PositionsService.ts
- apps/web/src/context/AuthContext.tsx
- apps/web/src/pages/register.tsx
- apps/web/tsconfig.json
- Use uuid to generate uuids in seed file
- Add new department in seed file for testing
- Create findAllInDepartmentName in positions module to look for positions in department we select
- Fix some inconsistencies with select input when completing logon
Closes [#208]
Create a new account with Azure login with different department and positions.
> 208 feature finish/fix issues with create profile screen

- apps/server/Dockerfile
Fixes render deploy, issue with linux image for some reason.
Closes [#]
> Install openssl in dockerfile

- apps/server/src/signatures/dto/update-signature-signer.dto.ts
- apps/server/src/signatures/signatures.controller.spec.ts
- apps/server/src/signatures/signatures.controller.ts
- apps/server/src/signatures/signatures.errors.ts
- apps/server/src/signatures/signatures.module.ts
- apps/server/src/signatures/signatures.service.spec.ts
- apps/server/src/signatures/signatures.service.ts
Implement service and controller for editing signature signers
Allows users to be able to modify who is able to sign for a signature.
Closes [#241]
Unit testing.
> [241] Implement editing signature signer

- apps/server/docker-compose.yml
The mfa-backend container was broken because secrets were not defined properly. Now it actually starts instead of restarting forever.
> fix docker compose for dev backend by adding env variables

- apps/server/src/auth/auth.service.ts
- apps/web/src/context/AuthContext.tsx
The issue was that the data encoding for the signature image is too big and is passed into the jwt encoding. This makes the jwt too big (> 4096 characters), which exceeds the browser limit and doesn't allow cookies to be set.
Fixed issue by removing signature link from the login controller so we dont' set the signature link in the jwt. Because of this, we have to make a fetchCurrentUser request to set the link in context.
5 big booms.
Big thanks to rishi for helping me.
Elvin where tf were you!!!
> Fix issue with auth

- apps/web/src/components/NavBar.tsx
- apps/web/src/components/createFormInstance/FormTemplateGrid.tsx
- apps/web/src/pages/create-instance/select-template.tsx
- apps/web/src/pages/template-directory.tsx
Only contributors and admins should be able to create a form template in the select form template page in create-instance pages
as an admin or contributor:
as a user:
Closes [#]
> only allow admins and contributors to create templates

- apps/web/src/components/SignFormInstancePreview.tsx
- apps/web/src/context/SignFormInstanceContext.tsx
We had excessive fetching in the form instance context whenever we clicked `Save and Continue`
Closes [#]
> Reduce fetching in sign form instance context
