sandboxnu/mfa-form-automator

- backend/package.json
- backend/src/app.module.ts
- backend/src/form/form.controller.spec.ts
- backend/src/form/form.controller.ts
- backend/src/form/form.dto.ts
- backend/src/form/form.module.ts
- backend/src/form/form.service.ts
- backend/src/main.ts
- backend/src/models/form.entity.ts
- backend/yarn.lock
Added a POST endpoint to create a Form. Kai had an issue with class-transformer not being installed so tight need to yarn install
Closes https://trello.com/c/vpxJiYO3/15-post-route-to-create-a-form
Please delete options that are not relevant.
Provide instructions so we can reproduce.
Manyal tested with postman
> created post endpoint to create form

- frontend/src/components/OverviewForm.tsx
- frontend/src/pages/index.tsx
- frontend/src/pages/test.tsx
- frontend/utils/types.tsx
Created a component for form overview in the dashboard. Also created a page (https/{{url}}/test) to test components.
Closes [story](https://trello.com/c/1CApI2hI/24-overview-form-compoment)
Please delete options that are not relevant.
Tested manually on common browsers to check functionality (Chrome, Safari, Firefox, Edge)
cd frontend, yarn dev --> manually check functionality on Chrome, Safari, Firefox, and Edge
> created overview form component

- frontend/src/components/NavBar.tsx
- frontend/src/components/OverviewForm.tsx
Changes color on navbar and overview form based on figma. 
Closes [story] - no story :(
Please delete options that are not relevant.
Tested manually on common browsers to check functionality (Chrome, Safari, Firefox, Edge)
> changed colors and font based on figma design

- package.json
The port for gen-client was set to 4000 when it should be 8080.
localhost:4000 to localhost:8080
> changed port for gen-client from 4000 to 8080

- apps/server/src/employees/employees.controller.spec.ts
- apps/server/src/employees/employees.service.ts
- apps/server/src/form-templates/form-templates.controller.ts
- apps/server/src/form-templates/form-templates.service.ts
- apps/server/src/positions/entities/position.entity.ts
- apps/server/src/signature-fields/dto/create-signature-field.dto.ts
- apps/server/src/signature-fields/entities/signature-field.entity.ts
- apps/server/src/signature-fields/signature-fields.controller.spec.ts
- apps/server/src/signature-fields/signature-fields.controller.ts
- apps/server/src/signature-fields/signature-fields.errors.ts
- apps/server/src/signature-fields/signature-fields.module.ts
- apps/server/src/signature-fields/signature-fields.service.spec.ts
- apps/server/src/signature-fields/signature-fields.service.ts
- apps/server/src/signatures/entities/signature.entity.ts
Closes [story](https://trello.com/c/1QRNOzRC/32-define-signaturefield-service-create-createmany-findone-findall-update)
Creates dtos, entity, service, controller, and module for SignatureField create, findOne, findAll, update, and delete operations.
Added logic in service and routes in controller, defined dtos and entity. 
todo later
> Signature fields

- apps/server/src/form-instances/form-instances.controller.ts
- apps/server/src/form-instances/form-instances.service.ts
- apps/server/src/positions/positions.controller.spec.ts
- apps/server/src/positions/positions.service.spec.ts
- apps/server/src/signatures/signatures.errors.ts
Added in the patch route for the state transition form.
Did some of the manual testing and it works.
> State transition form

- apps/server/src/form-instances/form-instance.errors.ts
- apps/server/src/form-instances/form-instances.controller.spec.ts
- apps/server/src/form-instances/form-instances.service.spec.ts
- apps/server/src/form-instances/form-instances.service.ts
- apps/server/src/form-templates/form-templates.service.ts
- apps/server/src/positions/positions.service.spec.ts
- apps/server/src/positions/positions.service.ts
Closes [Add validation when creating a new form instance in FormInstanceService](https://trello.com/c/vhvDLt6i/44-add-validation-when-creating-a-new-form-instance-in-forminstanceservice)
Add validation when creating form instances.
Updated form instance service and controller, and added unit tests.
- Try creating a new form instance?
- New unit tests to cover exception cases.
> Add validation and tests for form instance creation

- apps/server/src/form-instances/form-instances.module.ts
- apps/server/src/positions/positions.module.ts
> fix modules

- apps/web/src/pages/_app.tsx
Add font imports to fix font weights in form cards.
^
Check Vercel deployment.
> Add font imports

- apps/web/src/components/AvatarMap.tsx
- apps/web/src/components/NavBar.tsx
- apps/web/src/pages/formInstance.tsx
- apps/web/src/static/icons.tsx
- package.json
- yarn.lock
> Draft PR: Form instance view

- apps/server/nest-cli.json
- apps/server/prisma/seed.ts
- apps/server/src/form-instances/entities/form-instance.entity.ts
- apps/server/src/form-instances/form-instances.controller.ts
- apps/server/src/signatures/entities/signature.entity.ts
- apps/server/tsconfig.json
- apps/web/src/client/index.ts
- apps/web/src/client/models/EmployeeBaseEntity.ts
- apps/web/src/client/models/EmployeeEntity.ts
- apps/web/src/client/models/FormInstanceEntity.ts
- apps/web/src/client/models/FormTemplateBaseEntity.ts
- apps/web/src/client/models/FormTemplateEntity.ts
- apps/web/src/client/models/PositionEntity.ts
- apps/web/src/client/models/SignatureEntity.ts
- apps/web/src/client/models/SignatureFieldEntity.ts
- apps/web/src/client/services/DefaultService.ts
- apps/web/src/components/AvatarMap.tsx
- apps/web/src/components/FormInstance.tsx
- apps/web/src/pages/form-instances/[id].tsx
- apps/web/src/pages/formInstance.tsx
- package.json
- yarn.lock
Closes [Form instance view](https://trello.com/c/EGIEJnmC/63-form-instance-view)
New page
[X] This PR adds new dependencies
> Form instance backend view

- apps/web/src/components/NavBar.tsx
Closes [Create form instance/template button](https://trello.com/c/nrkFV83p/90-create-form-template-button)
New button
Check Vercel deploy and compare against Figma.
Figma mockup:
> Create form instance/template button

- apps/web/src/components/Layout.tsx
- apps/web/src/components/NavBar.tsx
- apps/web/src/components/TopBar.tsx
Closes [Remove search bar](https://trello.com/c/DhsLtAqc/91-update-header-and-remove-search-bar-from-dashboard)
Remove search bar
Remove search bar
- Make sure top header looks right
> Remove search bar

- apps/web/src/components/NavBar.tsx
> remove nav item

- apps/web/src/components/FormInstance.tsx
- apps/web/src/static/icons.tsx
> Form instance page touchup

- apps/web/src/components/AvatarMap.tsx
> text overlap for the avatar map

- apps/web/src/components/TopBar.tsx
- apps/web/src/static/icons.tsx
> blue avatar icon in the top right with the initials of the user

- .github/workflows/main.yml
> Fix format gh action

- apps/web/src/components/TopBar.tsx
Closes [story](https://trello.com/c/g3cvmkP7/93-add-user-profile-popper-with-logout)
Add user profile popper with logout
Basic popper for user
- Verify user popper is functional
> Add user signout menu

- apps/web/src/components/FormInstance.tsx
- apps/web/src/components/FormList.tsx
- apps/web/src/components/NavBar.tsx
- apps/web/src/components/TopBar.tsx
- apps/web/src/styles/globals.css
Closes [story](https://www.notion.so/sandboxnu/0ff8d90722bf435db9475c07e2311a2b?v=f7473b246d1742e395395cf955037121&p=2d2cbd6e60ef4e81bc0757a35cd8d2d9&pm=s)
Adds/Removes small UI elements, according to the Figma, and adds in CSS variables for the typography
Couple Quick Margin/Text changes in NavBar/TopBar and FormList
Removed the Search Bar and its imports from FormList
Manual Testing
CSS styles/components still behave as before, and followrf the checklist of things required in the ticket
> Typography and UI fixes

- .github/workflows/main.yml
- apps/web/src/components/FormCard.tsx
- apps/web/src/hooks/useForm.ts
> fix prettier hook

- apps/server/prisma/seed.ts
- apps/web/src/components/FormInstance.tsx
- apps/web/src/components/createFormInstance/CreateFormInstanceModal.tsx
- apps/web/src/components/createFormTemplate/CreateFormTemplateModal.tsx
- apps/web/src/components/createFormTemplate/PdfUpload.tsx
- apps/web/src/components/createFormTemplate/PdfViewer.tsx
- package.json
- yarn.lock
Closes [story](https://www.notion.so/sandboxnu/Render-PDF-forms-with-react-pdf-546b9c5e4bea4e46be744cc1188b03bb)
Added in support for the pdf uploading and rendering. The issue is occurring when you try to zoom in for the modal.
[X] This PR adds new dependencies
I tried to manually zoom in and stuff and that's when the error is occurring.
> Pdf upload file

- package.json
switched from localhost:3002 to 8080 for gen-client command
^
> gen-client fix

- apps/server/prisma/seed.ts
> added azure emails to seeding data

- apps/web/src/components/FormInstance.tsx
> temp move approve button to left

- apps/web/src/components/AvatarMap.tsx
- apps/web/src/static/icons.tsx
Fixed the color of the awaiting icon as well as the text size of the initials. Peep the slack for details.
Tested locally
> Fixed the color of the awaiting icon as well as the text size of the initials

- apps/web/public/mfa_favicon.svg
- apps/web/src/pages/_app.tsx
- apps/web/src/pages/_document.tsx
- apps/web/src/pages/index.tsx
Closes [story](https://www.notion.so/sandboxnu/Add-fav-icon-f0aab3a72a1a48b9a299e5b8fee45c6c)
Added a link to a blue flag for the fav icon. We were not able to get the ico file as a downloaded file. I believe that the issue is that we need to figure out a way to create a ico file. I think that the ico file is corrupted and for that reason we are unable to add local images as the icon. This may also be a NextJS issue which we need to figure out. The temporary fix for now can be just to keep the blue flag.
In-browser. Could you guys please just make sure that we aren't getting a ton of page redirects occurring because of this PR?
> Fixed the Fav-icon

- apps/server/prisma/seed.ts
- apps/web/src/components/FormInstance.tsx
- apps/web/src/components/createFormInstance/CreateFormInstanceModal.tsx
Seeds real forms from the MFA and creates several demo instances from them. Also fixed PDF display so it doesn't rerender on every user action. 
> Seed demo MFA forms and minor PDF display changes

- apps/server/prisma/seed.ts
- apps/web/src/pages/_document.tsx
> Seed file name

- apps/web/src/pages/signin.tsx
- Updated client secret in our Azure AD instance
- Refactored code to always show sign in button in case we login with an invalid account
- Client secret requires a change in .env file
- Now if we have a valid session, we still show the sign in page in case the user was not in the seeded db
Our client secret was expired so we were not able to login with Azure.
Previously, an invalid user would be stuck on the sign in page after login in.
Closes [#139]
N/A
> 139-bug-secret-expired

- apps/server/src/auth/auth.service.ts
- apps/web/src/context/AuthContext.tsx
- apps/web/src/context/types.ts
- apps/web/src/utils/formInstanceUtils.ts
- Add department id in jwt payload to user state in AuthContext
- Remove position fetch request in AuthContext
We want the user state object in AuthContext to contain department id so we can use it in the logic categorizing forms
Closes [#188]
Sign forms when my department is assigned.
> 188 feature add department id to jwt payload and remove position fetch request

- apps/server/src/form-instances/form-instances.module.ts
- apps/server/src/form-instances/form-instances.service.ts
- apps/server/src/postmark/postmark.module.ts
- apps/server/src/postmark/postmark.service.ts
- When a department or position is next in signer chain, send email to all users in department or position
- Move logic for emails to methods in form instance service
- Email notifications for departments and positions
- Cleans up code for emails
Closes [#187]
Signed form with position and department as next signer
Sign form as last user, making sure originator gets email that user has signed form and the form is ready for approval
> 187 feature handle email notifications to positions and departments

- apps/web/src/components/FormList.tsx
- apps/web/src/components/SearchAndSort.tsx
- apps/web/src/utils/formInstanceUtils.ts
This allows the user to search by filtering the form rows by only those that contain the search query.  Search is case insensitive.  You can search by the formInstance name.
The search bar should have an effect on what forms show up.
Closes [#199]
Tried searching by title and name, and saw forms displayed adjust with search query.
> Fix Search

- apps/server/prisma/seed.ts
Last PR broke seeding, need these seed file changes to be able to reseed.
Everyone will need to reset their local DB after these PRs go in, since some fields and migrations were renamed.
Run `yarn --cwd apps/server prisma migrate reset` from the root to reset prisma.
Closes [#]
> Update seed file

- apps/web/src/context/types.ts
> fix EmployeSCope type in types.tsx

- apps/web/src/components/NavBar.tsx
Only admins should be able to create form templates.
Closes [#]
> Only admins are able to create form templates #239

- apps/server/src/form-instances/dto/sign-form-instance.dto.ts
- apps/server/src/form-instances/form-instance.errors.ts
- apps/server/src/form-instances/form-instances.controller.ts
- apps/server/src/form-instances/form-instances.module.ts
- apps/server/src/form-instances/form-instances.service.ts
- apps/web/src/client/schemas.gen.ts
- apps/web/src/client/sdk.gen.ts
- apps/web/src/client/types.gen.ts
- apps/web/src/components/FormInstance.tsx
> Update endpoint to upload pdf when signing form instance

- apps/server/package.json
- apps/web/package.json
- yarn.lock
Delete an unused dependency.
Closes [#]
> Delete trpc dependency

- apps/web/src/components/AvatarMap.tsx
- apps/web/src/components/FormList.tsx
- apps/web/src/components/FormRow.tsx
- apps/web/src/components/OverviewRow.tsx
- apps/web/src/components/SignFormInstancePreview.tsx
Added a max modal height of 75vh.  If the height is exceeded, modal will be scrollable.  Modals are viewable from all of the form lists.  If the signed in user is not next up to sign the form, the "sign now" button is not shown.
Improves flexibility of previous modal design for longer lists of users.  
Closes [#325 ]
Created a form with max number of groups (right now 5) and checked styling changes. If you are not next to sign a form the option is removed.  Screenshots below:
> modal style changes

- apps/server/prisma/seed.ts
- apps/web/src/components/TopBar.tsx
- apps/web/src/context/AuthContext.tsx
Add user scope to user profile in top bar
Modify seed file so there is a contributor
> Show user scope in topbar

- apps/server/src/form-templates/form-templates.controller.ts
> fix field group not parsing correctly when creating form template

- apps/web/package.json
- yarn.lock
> Bump nextjs for middleware auth cve fix

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/epic.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/workflows/main.yml
- apps/web/src/components/AssignedAvatarGroup.tsx
- apps/web/src/components/FormImageCard.tsx
- apps/web/src/components/FormList.tsx
- apps/web/src/components/OverviewRow.tsx
- apps/web/src/components/createForm/FormButtons.tsx
Fixed responsiveness on dashboard, as well as card spacing.
Added a `Wrap` around cards in `OverviewRow` and changed the `FormList` layout from a `Grid` with `FormRows` to a `Table` component with rows/columns to improve responsiveness (also removed `FormRow` component).
Makes the site stay pretty when the tab is shrunk.
Closes #322
Tried it on two different browsers and different tab sizes.
> Fixed card and form table responsiveness

- apps/web/src/components/SearchAndSort.tsx
> Fix search bar

- apps/server/src/form-instances/form-instances.controller.ts
- apps/server/src/form-templates/form-templates.controller.ts
- apps/web/src/pages/create-instance/assign-groups.tsx
- apps/web/src/pages/create-instance/description.tsx
- apps/web/src/pages/create-instance/review.tsx
- apps/web/src/pages/create-instance/select-template.tsx
- apps/web/src/pages/create-instance/success.tsx
- apps/web/src/pages/create-template/description.tsx
- apps/web/src/pages/create-template/input-fields.tsx
- apps/web/src/pages/create-template/review.tsx
- apps/web/src/pages/create-template/success.tsx
- apps/web/src/pages/create-template/upload.tsx
Contributor
Create form templates
Create form instances
Admin
Directories
Create form templates
Create form instances
Viewer
Create from instances
Sign
Closes [#]
> update auth scopes

- apps/web/src/components/AzureSignout.tsx
- apps/web/src/components/SignIn.tsx
- apps/web/src/components/createForm/FormButtons.tsx
- apps/web/src/components/ui/toaster.tsx
- apps/web/src/context/AuthContext.tsx
- apps/web/src/context/types.ts
- apps/web/src/pages/_app.tsx
- apps/web/src/pages/register.tsx
Add toasts for error handling
Closes [#342 ]
> add toasts

- apps/web/src/components/FormList.tsx
- apps/web/src/components/SearchAndSort.tsx
> create jank sort menu

- apps/web/src/components/SignOut.tsx
- apps/web/src/pages/_app.tsx
- apps/web/src/pages/signin.tsx
> fix signin page bug and 404 render

- apps/server/src/employees/dto/update-employee.dto.ts
- apps/server/src/employees/employees.integration.spec.ts
- apps/web/src/client/schemas.gen.ts
- apps/web/src/client/types.gen.ts
- apps/web/src/components/SignaturePad.tsx
- apps/web/src/components/TopBar.tsx
- apps/web/src/components/UserSettings.tsx
- apps/web/src/context/AuthContext.tsx
- apps/web/src/context/types.ts
- apps/web/src/pages/register.tsx
- apps/web/src/utils/signatureUtils.ts
right now, changing position and department is disabled. can change signature though
Closes [#]
> implement account settings modal

- apps/web/src/components/createForm/FormButtons.tsx
- apps/web/src/context/SignFormInstanceContext.tsx
not vibe coded like elvins thats why it works
> Wait for router push to finish before setting state to false for loading

- apps/web/src/components/createForm/FormButtons.tsx
- apps/web/src/components/createFormInstance/FormView.tsx
- apps/web/src/components/createFormTemplate/createFormTemplateEditor/DraggableBoxFactory.tsx
- apps/web/src/components/createFormTemplate/createFormTemplateEditor/FormEditor.tsx
- apps/web/src/components/signFormInstance/PDFDisplayed.tsx
- apps/web/src/context/CreateFormTemplateContext.tsx
- apps/web/src/context/SignFormInstanceContext.tsx
- apps/web/src/utils/formTemplateUtils.ts
- apps/web/src/utils/misc.ts
https://github.com/user-attachments/assets/561fca9b-4014-48e5-a216-6a77f8e9b13c
Closes [#]
> vibe coded pdf infinite scroll

- apps/web/src/components/NavBar.tsx
- apps/web/src/pages/employee-directory.tsx
- apps/web/src/static/icons.tsx
hard coded a fake employee directory for showcase 😍 (will follow up w actual one) 
we need an employee directory
Closes [#]
this does not close the issue 
this has not been tested
- [x ] New feature (non-breaking change which adds functionality)
> Employee directory (part 1/?) 

- apps/web/src/components/SignFormInstancePreview.tsx
- apps/web/src/components/createForm/FormButtons.tsx
- apps/web/src/components/createForm/NameAndDescriptionBox.tsx
- apps/web/src/components/createFormInstance/AssignGroupsBox.tsx
- apps/web/src/components/createFormTemplate/ReviewBox.tsx
- apps/web/src/components/createFormTemplate/createFormTemplateEditor/FormEditor.tsx
- apps/web/src/components/signFormInstance/PDFDisplayed.tsx
- apps/web/src/pages/create-instance/assign-groups.tsx
- apps/web/src/pages/create-instance/description.tsx
- apps/web/src/utils/formInstanceUtils.ts
Start shifting create form instance usages of pdf view to form editor so we can display field boxes and stuff
Fix preview width of pdfs for creating form templates
Closes [#]
> PDF view improvements

- apps/server/src/field-group/entities/template-box.entity.ts
- apps/web/src/client/schemas.gen.ts
- apps/web/src/client/types.gen.ts
- apps/web/src/context/SignFormInstanceContext.tsx
- apps/web/src/context/types.ts
- apps/web/src/pages/sign-form/[id].tsx
User has to now sign multiple forms back to back instead of being able to sign multiple groups in one form.
> Fixed bug when a user is assigned multiple field groups

- apps/web/src/components/createFormTemplate/createFormTemplateEditor/CheckBox.tsx
- apps/web/src/components/createFormTemplate/createFormTemplateEditor/SignatureField.tsx
- apps/web/src/components/createFormTemplate/createFormTemplateEditor/TextField.tsx
disable resizing form editor input fields if editing disabled
before
https://github.com/user-attachments/assets/929e43b4-5da7-4c4a-99b4-55197b9b5072
after
https://github.com/user-attachments/assets/270f69d9-ecc3-4046-9018-22c487033afe
Closes [#]
> disable resizing form editor text fields if editing disabled

- .github/workflows/main.yml
- apps/server/prisma/schema.prisma
> use connection pool string

- apps/web/src/components/createFormTemplate/createFormTemplateEditor/FormEditor.tsx
Allows the user the spam the nav buttons
Closes [#]
> Fix spam page nav bug

- apps/web/src/components/createFormInstance/SignatureDropdown.tsx
- apps/web/src/pages/create-instance/assign-groups.tsx
- apps/web/src/pages/create-template/input-fields.tsx
When creating a form template, allow continuing only if a field is specified
Closes [#]
> create form template - allow continuing if a field is specified

- apps/web/src/components/FormPreview.tsx
- apps/web/src/context/SignFormInstanceContext.tsx
- apps/web/src/pages/sign-form/[id].tsx
- apps/web/src/utils/formInstanceUtils.ts
> Form instance preview should show signatures when signed

- apps/web/src/components/createFormInstance/SignatureDropdown.tsx
- apps/web/src/components/createFormInstance/SignatureDropdownSelect.tsx
- apps/web/src/components/createFormInstance/types.ts
Support assigning multiple employees to an assignee group.
Closes [#]
> Support assigning a list of users to an assignee group

- apps/web/src/components/createFormTemplate/createFormTemplateEditor/SignatureField.tsx
> Differentiate signature field box

- apps/web/src/components/createForm/FormButtons.tsx
- apps/web/src/components/createForm/FormLayout.tsx
- apps/web/src/pages/create-instance/assign-groups.tsx
- apps/web/src/pages/create-instance/description.tsx
- apps/web/src/pages/create-instance/review.tsx
- apps/web/src/pages/create-instance/select-template.tsx
- apps/web/src/pages/create-template/description.tsx
- apps/web/src/pages/create-template/input-fields.tsx
- apps/web/src/pages/create-template/review.tsx
- apps/web/src/pages/create-template/upload.tsx
- apps/web/src/pages/sign-form/[id].tsx
- apps/web/src/pages/sign-form/review/[id].tsx
Button served no functionality.
Closes [#]
> remove delete button from form buttons

- apps/server/src/form-instances/form-instances.controller.ts
- apps/server/src/form-instances/form-instances.integration.spec.ts
- apps/server/src/form-instances/form-instances.service.spec.ts
- apps/server/src/form-instances/form-instances.service.ts
- apps/server/src/form-instances/response/form-instance-find-all.response.ts
- apps/server/src/form-templates/entities/form-template.entity.ts
- apps/server/src/form-templates/form-templates.controller.ts
- apps/server/src/form-templates/form-templates.integration.spec.ts
- apps/server/src/form-templates/form-templates.service.ts
- apps/server/src/form-templates/responses/form-template-find-all.response.ts
- apps/web/src/client/@tanstack/react-query.gen.ts
- apps/web/src/client/schemas.gen.ts
- apps/web/src/client/sdk.gen.ts
- apps/web/src/client/types.gen.ts
- apps/web/src/components/ActiveFormList.tsx
- apps/web/src/components/TopBar.tsx
- apps/web/src/components/createFormInstance/FormTemplateGrid.tsx
- apps/web/src/pages/_app.tsx
- apps/web/src/pages/create-instance/select-template.tsx
- apps/web/src/pages/template-directory.tsx
Update backend endpoints to support pagination
Allows for infinite scroll when looking at all form instances page
Adds a view more button to load more templates for creating instances flow
Closes [#]
> Pagination for cases when fetching all templates or instances

- apps/web/src/components/FormPreview.tsx
- apps/web/src/components/createForm/FormButtons.tsx
- apps/web/src/components/createForm/FormLayout.tsx
- apps/web/src/components/createForm/NameAndDescriptionBox.tsx
- apps/web/src/components/createFormInstance/AssignGroupsBox.tsx
- apps/web/src/components/createFormInstance/ReviewBox.tsx
- apps/web/src/components/createFormTemplate/ReviewBox.tsx
- apps/web/src/components/createFormTemplate/createFormTemplateEditor/FormEditor.tsx
- apps/web/src/components/createFormTemplate/createFormTemplateEditor/TextField.tsx
- apps/web/src/components/createFormTemplate/utils.ts
- apps/web/src/components/signFormInstance/PDFDisplayed.tsx
- apps/web/src/components/signFormInstance/ReviewBox.tsx
- apps/web/src/context/CreateFormInstanceContext.tsx
- apps/web/src/pages/create-instance/description.tsx
- apps/web/src/pages/create-instance/select-template.tsx
- apps/web/src/pages/create-template/description.tsx
- apps/web/src/pages/create-template/input-fields.tsx
- apps/web/src/pages/create-template/upload.tsx
- apps/web/src/pages/sign-form/[id].tsx
- apps/web/src/pages/sign-form/review/[id].tsx
- apps/web/src/utils/formInstanceUtils.ts
Try to support pdf resizing
Closes [#]
> Attempt pdf window resizing

- apps/web/src/components/SignIn.tsx
- apps/web/src/components/createForm/FormButtons.tsx
- apps/web/src/context/AuthContext.tsx
- apps/web/src/context/SignFormInstanceContext.tsx
Form field text boxes no longer show borders and have transparent backgrounds.
Closes [#]
> Fix form field text box rendering
